name: A workflow for Population Information App
on: push

jobs:
  build:
    name: Population Information action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup network
        run: |
          docker network create --driver bridge set08103_assessment
          docker pull mongo
          docker run -d --name mongo-dbserver --network set08103_assessment mongo
      - name: Build with Maven
        run: mvn package
      - name: Build
        run: docker build -t set08103_assessment .
      - name: Run image
        run: docker run --network set08103_assessment --name semcontainer set08103_assessment
      - name: view logs
        run: docker logs semcontainer

